Repository OpenDevicePartnership/embedded-batteries, pull requests merged in 2025-05, with the labels that each got.

#25 Add support for Smart Battery ChargingCurrent() and ChargingVoltage()
  embedded-batteries-async/src/smart_battery.rs
  embedded-batteries/src/smart_battery.rs
Labels: enhancement

#27 Add author and msrv to Cargo.tomls
  embedded-batteries-async/Cargo.toml
  embedded-batteries/Cargo.toml
Labels: documentation, enhancement

#28 Enable semver checks, reduce crate keywords to 5 in Cargo.toml and point embedded-batteries to version
  .github/workflows/check.yml
  .github/workflows/nostd.yml
  embedded-batteries-async/Cargo.toml
  embedded-batteries/Cargo.toml
Labels: enhancement

#29 pull embedded-batteries from crates.io
  embedded-batteries-async/Cargo.toml
Labels: bug
